services:
  local-s3:
    image: localstack/localstack
    ports:
      - 4566:4566
    environment:
      - LOCALSTACK_SERVICES=s3
      - AWS_ACCESS_KEY_ID=something_not_empty
      - AWS_SECRET_ACCESS_KEY=something_not_empty
    healthcheck:
      test: ["CMD", "aws", "s3", "--endpoint-url", "http://localhost:4566", "ls"]
      interval: 5s
      timeout: 60s
      retries: 30
